//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidad;

    public partial class CDocumentosEntities : DbContext
    {
        public CDocumentosEntities()
            : base("name=CDocumentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Documento> Documentoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
    
        public virtual ObjectResult<BuscaDepartamentos_Result> BuscaDepartamentos(string nombre_departamento)
        {
            var nombre_departamentoParameter = nombre_departamento != null ?
                new ObjectParameter("nombre_departamento", nombre_departamento) :
                new ObjectParameter("nombre_departamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscaDepartamentos_Result>("BuscaDepartamentos", nombre_departamentoParameter);
        }
    
        public virtual ObjectResult<BuscaEmpleados_Result> BuscaEmpleados(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscaEmpleados_Result>("BuscaEmpleados", nombreParameter);
        }
    
        public virtual ObjectResult<BuscaDocumentos_Result> BuscaDocumentos(string departamento_origen)
        {
            var departamento_origenParameter = departamento_origen != null ?
                new ObjectParameter("departamento_origen", departamento_origen) :
                new ObjectParameter("departamento_origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscaDocumentos_Result>("BuscaDocumentos", departamento_origenParameter);
        }
    }
}
