//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoId { get; set; }
        public string NombreEmpleado { get; set; }
        public string CorreoElectronico { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public System.DateTime FechaCreacionEmpleado { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
        public virtual Documento Documento { get; set; }
    }
}
